In [1]:
from numpy import array
from scipy.linalg import svd
A=array([[1,2],[3,4],[5,6]])
print("A=",A)
print("shape of array A:",A.shape)
print("")
U,s,VT=svd(A)
print("U=",U)
print("shape of matrix U:",U.shape)
print("")
print("Sigma(diagonal matrix),s=",s)
print("shape of matrix sigma:",s.shape)
print("")
print("transpose matrix: VT=",VT)
print("shape of VT:",VT.shape)

A= [[1 2]
 [3 4]
 [5 6]]
shape of array A: (3, 2)

U= [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
shape of matrix U: (3, 3)

Sigma(diagonal matrix),s= [9.52551809 0.51430058]
shape of matrix sigma: (2,)

transpose matrix: VT= [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
shape of VT: (2, 2)


In [3]:
from numpy import array,diag,dot,zeros
from scipy.linalg import svd
A=array([[1,2],[3,4],[5,6]])
print("A=",A)
print("shape of matrix A",A.shape)
U,s,VT=svd(A)
print("U=",U)
print("shape of matrix U:",U.shape)
print("sigma diagonal matrix s=",s)
print("shape of matrix s",s.shape)
print("VT=",VT)
print("shape of diagonal",VT.shape)
sigma=zeros((A.shape[0],A.shape[1]))
sigma[:A.shape[1],:A.shape[1]]=diag(s)
B=U.dot(sigma.dot(VT))
print("reconstructed matrix:",B)

A= [[1 2]
 [3 4]
 [5 6]]
shape of matrix A (3, 2)
U= [[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]]
shape of matrix U: (3, 3)
sigma diagonal matrix s= [9.52551809 0.51430058]
shape of matrix s (2,)
VT= [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]
shape of diagonal (2, 2)
reconstructed matrix: [[1. 2.]
 [3. 4.]
 [5. 6.]]


In [7]:
from numpy import array,diag,zeros
from scipy.linalg import pinv
from numpy.linalg import svd
a=array([[1,2],[3,4],[5,6]])
print("A=",A)
print("pseudoinverse of matrix A(pinv):")
print(pinv(A))
d=1.0/s
D=zeros(A.shape)
D[:A.shape[1],:A.shape[1]]=diag(d)
B=VT.T.dot(D.T).dot(U.T)
print("pseudoinverse of matrix A(svd):")
print(B)

A= [[1 2]
 [3 4]
 [5 6]]
pseudoinverse of matrix A(pinv):
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
pseudoinverse of matrix A(svd):
[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]
